framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: session.handler.native_file
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto
        cookie_samesite: lax
    form:
        enabled: true
        csrf_protection:
            enabled: true
            field_name: '_token'